version: "3"

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8969:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    hostname: localhost
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5469:5432"
    environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_HOST_AUTH_METHOD=trust